### ISSUE TITLE
[Suggestion] Killing 575 after Warhead Detonates

### ISSUE THREAD

**Issue by DinoNuggets2** [Marco15453/SCP-575#1]
Just a simple suggestion, so after the warhead detonates, make it configurable if 575 dies by it, and a CASSIE announcement saying how 575 died, for example:

Once the warhead detonates, 575 is disabled for the rest of the round, and CASSIE announces, "S C P 5 7 5 successfully terminated by Alpha Warhead"

**Comment by Marco15453** [comment]
This has been added into the release v4.3.0
